include:
  - project: ci/hub
    ref:     v2.x
    file:    image-builder.yaml

stages:
  - image-builder

Build PHP 8.1 Image:
  extends: .ci:image-builder
  script:
    - ci-builder php:8.1-fpm-alpine

Build PHP 8.2 Image:
  extends: .ci:image-builder
  script:
    - ci-builder php:8.2-fpm-alpine

Build PHP 8.3 Image:
  extends: .ci:image-builder
  script:
    - ci-builder php:8.3-fpm-alpine
