#::PROJECT:CI:PHP-UPSTREAM
default:
  image: ${CI_REGISTRY}/the-platform/container-images/docker-shell:latest
  services:
    - docker:dind
  tags:
    - docker-in-docker

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CREATE_CONTEXT: 1

stages:
  - builder

.ci:image-build:
  stage: builder
  variables:
    GIT_DEPTH: 1
  before_script:
    - ci/ci-setup-environment
  artifacts:
    name: "build-artifacts-${CI_PROJECT_NAME}"
    paths:
      - .artifacts
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "pipeline"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG =~ /trigger/
  retry: 1

Build PHP 8.1 Image:
  extends: .ci:image-build
  script:
    - ci/ci-builder php:8.1-fpm-alpine

Build PHP 8.2 Image:
  extends: .ci:image-build
  script:
    - ci/ci-builder php:8.2-fpm-alpine

Build PHP 8.3 Image:
  extends: .ci:image-build
  script:
    - ci/ci-builder php:8.3-fpm-alpine
