#!/bin/bash
set -eu
set -o pipefail
source "config.ci"
BASE=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

export PATH="${BASE}/ci:${PATH}"

printf -- "BUILDS:\n"
for version in ${PHP_UPSTREAM}
do
  printf -- "  %s\n" "${version}"
done

for version in ${PHP_UPSTREAM}
do
  if pv=$(get-php-version "${version}")
  then
    if [[ ${pv} =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
    then
      major="${pv%.*}"
      minor="${pv##*.}"
      flavor="${version#*-}"
      shadow-text 0 "${flavor}"
      shadow-text 6 "${pv}"
      image-builder "${version}" "${flavor}" "${pv}" "${major}" "${minor}"
    else
      printf -- "ERROR: unable parse upstream PHP version ...\n"
      exit 100
    fi
  else
    printf -- "ERROR: unable to get upstream PHP version ...\n"
    exit 200
  fi
done
