ARG UPSTREAM=php:8.4-fpm-alpine
FROM ${UPSTREAM}
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN apk upgrade --no-cache && \
    apk add --no-cache tini && \
    chmod +x /usr/local/bin/install-php-extensions && \
    IPE_DONT_ENABLE=1 install-php-extensions \
      bcmath \
      bz2 \
      calendar \
      exif \
      ftp \
      gd \
      gettext \
      gmp \
      imagick \
      imap \
      intl \
      ldap \
      lzf \
      memcache \
      memcached \
      mongodb  \
      mysqli \
      newrelic \
      pcntl \
      opcache \
      pdo_mysql \
      pdo_pgsql	\
      pgsql \
      redis \
      soap \
      sockets \
      xdebug \
      yaml \
      xsl \
      zstd \
      zip  && \
    find /usr/local/etc/php/conf.d -type f -name "*.ini" -not -name "docker-fpm.ini" -not -name "docker-php-ext-sodium.ini" -exec mv {} {}-disabled \;
COPY --chmod=0755 enable-php-extensions /usr/local/bin/enable-php-extensions
