#!/bin/bash
set -eu
source "config.ci"
echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY" &>/dev/null
docker run --quiet --privileged --rm tonistiigi/binfmt --install all &>/dev/null
docker buildx inspect "${DOCKER_BUILDER}" --bootstrap || docker buildx create --use --bootstrap --name "${DOCKER_BUILDER}"
